name: Compile MRS for gambino-proxy

permissions:
  contents: write

on:
  workflow_dispatch:  # Ручной запуск
  push:
    branches: [ master ]
    paths:
      - 'Clash/gambino-proxy.yaml'  # Запуск только при изменениях
  pull_request:
    branches: [ master ]
    paths:
      - 'Clash/gambino-proxy.yaml'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Для коммитов
        ref: master  # Фиксируем ветку

    - name: Download latest mihomo binary
      run: |
        # Получаем тег последней версии
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
        echo "Downloading mihomo version: $LATEST_RELEASE"
        # Скачиваем бинарник
        wget https://github.com/MetaCubeX/mihomo/releases/download/${LATEST_RELEASE}/mihomo-linux-amd64-v${LATEST_RELEASE#v}.gz
        gunzip mihomo-linux-amd64-v${LATEST_RELEASE#v}.gz
        chmod +x mihomo-linux-amd64-v${LATEST_RELEASE#v}
        mv mihomo-linux-amd64-v${LATEST_RELEASE#v} mihomo
        # Добавляем в PATH без sudo
        export PATH="$PWD:$PATH"
        echo "PATH updated, mihomo ready"

    - name: Compile gambino-proxy to MRS
      env:
        NO_SKIP: true
      run: |
        # Компиляция в Clash/
        mihomo convert-ruleset domain yaml Clash/gambino-proxy.yaml Clash/gambino-proxy.mrs
        # Проверка (для логов)
        ls -la Clash/gambino-proxy.mrs

    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Commit and push MRS file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Clash/gambino-proxy.mrs
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-compile gambino-proxy.mrs from gambino-proxy.yaml on ${{ env.DATE }} [skip ci]"
          git push
        fi

    - name: Upload MRS artifact (for download)
      uses: actions/upload-artifact@v4
      with:
        name: gambino-proxy-mrs
        path: Clash/gambino-proxy.mrs
        retention-days: 7

    - name: Delete temp files
      run: |
        rm -f mihomo*.gz mihomo  # Чистим бинарник тоже
