name: Compile MRS for gambino-proxy

permissions:
  contents: write

on:
  workflow_dispatch:  # Ручной запуск
  push:
    branches: [ master ]
    paths:
      - 'Clash/gambino-proxy.yaml'  # Запуск только при изменениях
  pull_request:
    branches: [ master ]
    paths:
      - 'Clash/gambino-proxy.yaml'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Для коммитов
        ref: master  # Фиксируем ветку

    - name: Download mihomo v1.19.15 binary
      run: |
        set -e  # Остановка на ошибках
        VERSION="v1.19.15"
        echo "Downloading mihomo version: $VERSION"
        # Скачиваем v3-вариант для amd64 (modern CPU)
        wget https://github.com/MetaCubeX/mihomo/releases/download/${VERSION}/mihomo-linux-amd64-v3-v${VERSION#v}.gz
        gunzip mihomo-linux-amd64-v3-v${VERSION#v}.gz
        chmod +x mihomo-linux-amd64-v3-v${VERSION#v}
        mv mihomo-linux-amd64-v3-v${VERSION#v} mihomo
        # Проверка установки
        ./mihomo -h || { echo "Error: mihomo failed to install"; exit 1; }

    - name: Compile gambino-proxy to MRS
      env:
        NO_SKIP: true
      run: |
        set -e  # Остановка на ошибках
        # Проверка файла mihomo
        if [ ! -x "./mihomo" ]; then
          echo "Error: mihomo binary not found or not executable"
          exit 1
        fi
        # Компиляция в Clash/ (./mihomo — относительный путь)
        ./mihomo convert-ruleset domain yaml Clash/gambino-proxy.yaml Clash/gambino-proxy.mrs
        # Проверка (для логов)
        ls -la Clash/gambino-proxy.mrs

    - name: Get current date
      id: date
      run: echo "DATE=$(date -u +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV  # ISO с T (UTC)

    - name: Commit and push MRS file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Generating .mrs ${{ env.DATE }} [skip ci]" -a || echo "No changes to commit"
        git push

    - name: Upload MRS artifact (for download)
      uses: actions/upload-artifact@v4
      with:
        name: gambino-proxy-mrs
        path: Clash/gambino-proxy.mrs
        retention-days: 7

    - name: Delete temp files
      run: |
        rm -f mihomo*.gz mihomo  # Чистим gz и бинарник
